substitutions:
  _ARCVERSION: '3.6.2'
  _SPARKVERSION: '3.0.1'
  _SCALAVERSION: '2.12'
  _HADOOPVERSION: '3.2.0'
  _ARCJUPYTERVERSION: '3.11.0'
  _ARCIMAGEVERSION: '1.17.0'
  _ARCJUPYTERIMAGEVERSION: '1.8.0'
  _FROMIMAGESPARK: 'ghcr.io/tripl-ai/spark:spark_3.0.1_scala_2.12_hadoop_3.2.0'
steps:
- name: "gcr.io/cloud-builders/docker"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'ARC_VERSION=$_ARCVERSION'
  - 'SPARK_VERSION=$_SPARKVERSION'
  - 'SCALA_VERSION=$_SCALAVERSION'
  - 'HADOOP_VERSION=$_HADOOPVERSION'
  - 'ARC_JUPYTER_VERSION=$_ARCJUPYTERVERSION'
  - 'ARC_IMAGE_VERSION=$_ARCIMAGEVERSION'
  - 'ARC_JUPYTER_IMAGE_VERSION=$_ARCJUPYTERIMAGEVERSION'
  - 'FROM_IMAGE=${_FROMIMAGESPARK}'
  args: [
      'build',
      '--build-arg',
      'FROM_IMAGE=${_FROMIMAGESPARK}',
      '--build-arg',
      'ARC_VERSION=${_ARCVERSION}',
      '--build-arg',
      'SPARK_VERSION=${_SPARKVERSION}',
      '--build-arg',
      'SCALA_VERSION=${_SCALAVERSION}',
      '--build-arg',
      'HADOOP_VERSION=${_HADOOPVERSION}',
      '--build-arg',
      'ARC_JUPYTER_VERSION=${_ARCJUPYTERVERSION}',
      '--file',
      './arc/Dockerfile',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-mod1:${BUILD_ID}',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-mod1:latest',
      '.'
  ]
- name: "gcr.io/cloud-builders/docker"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'ARC_VERSION=$_ARCVERSION'
  - 'SPARK_VERSION=$_SPARKVERSION'
  - 'SCALA_VERSION=$_SCALAVERSION'
  - 'HADOOP_VERSION=$_HADOOPVERSION'
  - 'ARC_JUPYTER_VERSION=$_ARCJUPYTERVERSION'
  - 'ARC_IMAGE_VERSION=$_ARCIMAGEVERSION'
  - 'ARC_JUPYTER_IMAGE_VERSION=$_ARCJUPYTERIMAGEVERSION'
  - 'FROM_IMAGE=gcr.io/jupyterinstance-223809/arc-mod1:${BUILD_ID}'
  args: [
      'build',
      '--build-arg',
      'FROM_IMAGE=gcr.io/jupyterinstance-223809/arc-mod1:${BUILD_ID}',
      '--build-arg',
      'ARC_JUPYTER_VERSION=${_ARCJUPYTERVERSION}',
      '--file',
      './arc-jupyter/Dockerfile',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-jupyter-mod1:${BUILD_ID}',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-jupyter-mod1:latest',
      '.'
  ]
images:
- 'gcr.io/jupyterinstance-223809/arc-jupyter-mod1:${BUILD_ID}'
- 'gcr.io/jupyterinstance-223809/arc-jupyter-mod1:latest'
- 'gcr.io/jupyterinstance-223809/arc-mod1:${BUILD_ID}'
- 'gcr.io/jupyterinstance-223809/arc-mod1:latest'

timeout: 1200s