substitutions:
  _ARCVERSION: '3.6.2'
  _SPARKVERSION: '3.0.1'
  _SCALAVERSION: '2.12'
  _HADOOP_VERSION: '3.2.0'
  _ARCJUPYTERVERSION: '3.11.0'
  _ARCIMAGEVERSION: '1.17.0'
  _ARCJUPYTERIMAGEVERSION: '1.8.0'
  _FROMIMAGESPARK: 'ghcr.io/tripl-ai/spark:spark_${_SPARKVERSION}_scala_${_SCALAVERSION}_hadoop_${_HADOOPVERSION}'
steps:
- name: "gcr.io/cloud-builders/docker"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'ARC_VERSION=$_ARCVERSION'
  - 'SPARK_VERSION=$_SPARKVERSION'
  - 'SCALA_VERSION=$_SCALAVERSION'
  - 'HADOOP_VERSION=$_HADOOPVERSION'
  - 'ARC_JUPYTER_VERSION=$_ARCJUPYTERVERSION'
  - 'ARC_IMAGE_VERSION=$_ARCIMAGEVERSION'
  - 'ARC_JUPYTER_IMAGE_VERSION=$_ARCJUPYTERIMAGEVERSION'
  - 'FROM_IMAGE=$_FROMIMAGESPARK'
  args: [
      'build',
      '--build-arg',
      'FROM_IMAGE=${_FROMIMAGE}',
      '--build-arg',
      'ARC_VERSION=${_ARCVERSION}',
      '--build-arg',
      'SPARK_VERSION=${_SPARKVERSION}',
      '--build-arg',
      'HADOOP_VERSION=${_HADOOPVERSION}',
      '--build-arg',
      'ARC_JUPYTER_VERSION=${_ARCJUPYTERVERSION}',
      '--file',
      './arc/Dockerfile',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-mod1',
      '.'
  ]
- name: "gcr.io/cloud-builders/docker"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'ARC_VERSION=$_ARCVERSION'
  - 'SPARK_VERSION=$_SPARKVERSION'
  - 'SCALA_VERSION=$_SCALAVERSION'
  - 'HADOOP_VERSION=$_HADOOPVERSION'
  - 'ARC_JUPYTER_VERSION=$_ARCJUPYTERVERSION'
  - 'ARC_IMAGE_VERSION=$_ARCIMAGEVERSION'
  - 'ARC_JUPYTER_IMAGE_VERSION=$_ARCJUPYTERIMAGEVERSION'
  - 'FROM_IMAGE=$_FROMIMAGESPARK'
  - 'FROM_IMAGE=gcr.io/jupyterinstance-223809/arc-mod1'
  args: [
      'build',
      '--build-arg',
      'FROM_IMAGE=gcr.io/jupyterinstance-223809/arc-mod1',
      '--build-arg',
      'ARC_JUPYTER_VERSION=${_ARCJUPYTERVERSION}',
      '--file',
      './arc-jupyter/Dockerfile',
      '-t',
      'gcr.io/jupyterinstance-223809/arc-jupyter-mod1',
      '.'
  ]
images:
- 'gcr.io/jupyterinstance-223809/arc-jupyter-mod1'
- 'gcr.io/jupyterinstance-223809/arc-mod1'

timeout: 1200s