substitutions:
  _FROMIMAGE: 'ghcr.io/tripl-ai/arc:arc_3.6.2_spark_3.0.1_scala_2.12_hadoop_3.2.0_1.17'
  _ARCJUPYTERVERSION: '3.11.0'
steps:
- name: "gcr.io/cloud-builders/docker"
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'ARC_VERSION=3.6.2'
  - 'SPARK_VERSION=3.0.1'
  - 'SCALA_VERSION=2.12'
  - 'HADOOP_VERSION=3.2.0'
  - 'ARC_JUPYTER_VERSION=3.11.0'
  - 'ARC_IMAGE_VERSION=1.17.0'
  - 'ARC_JUPYTER_IMAGE_VERSION=1.8.0'
  entrypoint: 'bash'
  args: ['build -f arc-jupyter/Dockerfile --build-arg="FROM_IMAGE=ghcr.io/tripl-ai/arc:arc_3.6.2_spark_3.0.1_scala_2.12_hadoop_3.2.0_1.17" --build-arg="ARC_JUPYTER_VERSION=3.11.0" ./arc-jupyter']
